#shell
#set-option -g default-shell /usr/local/bin/zsh
set-option -g default-shell /bin/bash

# prefix key 
set -g prefix C-t
unbind C-b
bind C-t send-prefix

# key stroak
set -g escape-time 1

# index
set -g base-index 1
setw -g pane-base-index 1

# split-window
bind | split-window -h
bind - split-window -v

# set vim like key-bind
set-window-option -g mode-keys vi

bind-key v copy-mode \; display "Copy mode!"
bind-key -t vi-copy Enter copy-pipe "reattach-to-user-namespace pbcopy"
bind-key -t vi-copy y copy-pipe "reattach-to-user-namespace pbcopy"
bind-key p paste-buffer

# vim <=> tmux
set-option -g default-command "reattach-to-user-namespace -l zsh"

# copy-mode

bind-key -t vi-copy Escape clear-selection
bind-key -t vi-copy C-c cancel
bind-key -t vi-copy C-v rectangle-toggle
bind-key -t vi-copy V select-line

bind-key -t vi-copy C-a start-of-line
bind-key -t vi-copy C-e end-of-line

bind-key -t vi-copy w next-word
bind-key -t vi-copy e next-word-end
bind-key -t vi-copy b previous-word

bind-key -t vi-copy g top-line
bind-key -t vi-copy G bottom-line

bind-key -t vi-copy / search-forward
bind-key -t vi-copy / search-backward
bind-key -t vi-copy C-n page-up
bind-key -t vi-copy C-f page-down
bind-key -t vi-copy C-u scroll-up
bind-key -t vi-copy C-d scroll-down

# window & pane

bind-key -r C-h select-window -t :-
bind-key -r C-l select-window -t :+

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

bind-key -r H resize-pane -L 5
bind-key -r J resize-pane -D 5
bind-key -r K resize-pane -U 5
bind-key -r L resize-pane -R 5

bind-key -n C-o select-pane -t :.+

# status bar

set-option -g status-position top
set-option -g status-left-length 90
set-option -g status-right-length 90
set-option -g status-left '#H:[#P]'
set-option -g status-interval 1
set-option -g status-justify centre

# reload 
bind r source-file ~/.tmux.conf \; display "Reloaded!"

######################################################
# tpm
######################################################

set -g @plugins '~/.tmux/plugins/tpm'
set -g @plugins '/tmux-yank'
set -g @plugins '/tmux-open'
set -g @plugins '/tmux-battery'
set -g @plugins '/tmux-sensible'
set -g @plugins 'seebi/tmux-colors-solarized'

run '~/.tmux/plugins/tpm/tpm'
