#shell
set-option -g default-shell /bin/zsh

# prefix key 
set -g prefix C-t
unbind C-b
bind C-t send-prefix

# key stroak
set -sg escape-time 1

# index
set -g base-index 1
setw -g pane-base-index 1

# split-window
bind | split-window -h
bind - split-window -v

# set vim like key-bind
bind h select-pane -L
bind k select-pane -D
bind j selecct-pane -U
bind l select-pane -R
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# mouse
set w -g mouse

# colors
set-option -g defalut-terminal screen-256color
 
# reload 
bind r source-file ~/.tmux.conf \; display "Reloaded!"
 
